version: '3'

services:
  influxdb:
    image: influxdb
    ports: 
      - "8086:8086"
    volumes:
      - "influx_data:/var/lib/influxdb"
      - "influx2_data:/var/lib/influxdb2"
      - "influx_config:/etc/influxdb"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=MF
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=MFadmin
      - GF_SECURITY_ADMIN_PASSWORD=MFadmin
    volumes:
      - "grafana_data:/var/lib/grafana"
    depends_on:
      - influxdb  
    links:
      - influxdb:influxdb  

volumes:
  grafana_data:
    driver: local
  influx_data:
    driver: local
  influx_config:
    driver: local